name: Caching Demo .NET

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      INSTALLATION_PATH: './.dotnet'
      
    steps:
    - name: Cache dotnet
      id: cache-dotnet
      uses: actions/cache@v4
      with:
        path: ${{ env.INSTALLATION_PATH }}
        key: ${{ runner.os }}-dotnet-6
        restore-keys: ${{ runner.os }}-dotnet-6
        
    - uses: actions/checkout@v3
    - name: Setup .NET
      if: steps.cache-dotnet.outputs.cache-hit != 'true'
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Check default dotnet version
      run: dotnet --version
    
    - name: set installed/cached dotnet path
      run: echo "${{ env.INSTALLATION_PATH }}" | Out-File -FilePath $ENV:GITHUB_PATH -Encoding utf8 -Append
    
    - name: Check installed/cached dotnet version
      run: dotnet --version
      
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
