name: Data Sharing using Upload-Download Artifacts
on:
  workflow_dispatch:
jobs:
  UploadJob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - uses: actions/upload-artifact@v3
        with:
          name: DotNetBuild
          path: dist
  DownloadJob:
    runs-on: ubuntu-latest
    needs: UploadJob
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: DotNetBuild
          path: build
      - run: zip -r build.zip build/
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "build.zip"
